[project]
name = "tiet-notegen-v2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "requests>=2.32.4",
    "rich>=14.0.0",
    "textual>=3.5.0",
]
